### ISSUE TITLE
Error on showing sprint

### ISSUE THREAD

**Issue by SebastiaanKloos** [gitscrum-ce/laravel-gitscrum#189]
<p>ErrorException in helpers.php line 532:
htmlspecialchars() expects parameter 1 to be string, object given (View: {path to project}/resources/views/sprints/show.blade.php)</p>

**Comment by renatomarinho** [comment]
@SebastiaanKloos This is a bug known to me, this occurs when you don't have description.

**Comment by SebastiaanKloos** [comment]
@renatomarinho I've added the descriptions but this error still occurs.

**Comment by SebastiaanKloos** [comment]
@renatomarinho I checked the product_backlogs and sprints tables.

**Comment by SebastiaanKloos** [comment]
@renatomarinho This error is also occurring on this page:
product-backlogs/show

**Comment by renatomarinho** [comment]
@SebastiaanKloos I did a fix for that, please do a pull and test again.
